name: Build & Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --base-href /MyBucketList/

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/MyBucketList --branch=gh-pages
        env:
          CI: true
