name: Build & Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npx ng build --configuration production --base-href /dudoo/

      - name: Set Git identity for deployment
        run: |
          git config user.name "dudoo-bot"
          git config user.email "bot@dudoo.app"


      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/dudoo --branch=gh-pages --no-silent --repo=https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ftiannn/dudoo.git
        env:
          CI: true
